/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Events */
        get: operations["list_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events/{event_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Event */
        get: operations["get_event_api_events__event_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/distributions/{quantity}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Distribution
         * @description A precomputed binned spectrum.
         *
         *     Returned as-is rather than through a response model: the payload is a
         *     pipeline artifact with its own schema_version, and re-declaring its
         *     shape here would create a second definition to keep in step.
         */
        get: operations["get_distribution_api_distributions__quantity__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Models */
        get: operations["list_models_api_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * EventListResponse
         * @description A page of event summaries.
         */
        EventListResponse: {
            /**
             * Total
             * @description Matching events before pagination
             */
            total: number;
            /**
             * Count
             * @description Events in this page
             */
            count: number;
            /** Events */
            events: components["schemas"]["EventSummary"][];
        };
        /**
         * EventPayload
         * @description One complete event, as delivered to the browser.
         */
        EventPayload: {
            /**
             * Schema Version
             * @default 1.0
             */
            schema_version: string;
            /** Event Id */
            event_id: string;
            /**
             * Data Kind
             * @description Required. 'measured' events carry no truth label.
             * @enum {string}
             */
            data_kind: "measured" | "simulated";
            /** Mc Process */
            mc_process?: string | null;
            /** Truth Label */
            truth_label?: ("signal" | "background") | null;
            /** Mc Weight */
            mc_weight?: number | null;
            /**
             * Experiment
             * @default ATLAS
             */
            experiment: string;
            /**
             * Collision Energy Tev
             * @description Beam configuration, not a per-event measurement
             * @default 13
             */
            collision_energy_tev: number;
            /** Run Number */
            run_number?: number | null;
            /** Event Number */
            event_number?: number | null;
            /** Objects */
            objects: components["schemas"]["ReconstructedObject"][];
            missing_energy?: components["schemas"]["MissingEnergy"] | null;
            /** Derived */
            derived?: {
                [key: string]: number;
            };
            prediction?: components["schemas"]["Prediction"] | null;
            /** Prediction Unavailable Reason */
            prediction_unavailable_reason?: string | null;
            provenance: components["schemas"]["Provenance"];
        };
        /**
         * EventSummary
         * @description Lightweight row for the explore/browse list.
         *
         *     Deliberately small: the browser fetches many of these and exactly one full
         *     payload. Keeping them separate is what stops the list view from pulling
         *     kinematics for hundreds of events.
         */
        EventSummary: {
            /** Event Id */
            event_id: string;
            /**
             * Data Kind
             * @enum {string}
             */
            data_kind: "measured" | "simulated";
            /** Category */
            category: string;
            /** N Objects */
            n_objects: number;
            /** N Leptons */
            n_leptons: number;
            /** Score */
            score?: number | null;
            /**
             * Headline
             * @description One or two display quantities, e.g. m_4l
             */
            headline?: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * MissingEnergy
         * @description Missing transverse energy: the imbalance implying unseen particles.
         */
        MissingEnergy: {
            /**
             * Magnitude
             * @description GeV
             */
            magnitude: number;
            /**
             * Phi
             * @description radians
             */
            phi: number;
        };
        /**
         * ModelInfo
         * @description Public description of a registered model.
         *
         *     Limitations are part of the response, not a footnote elsewhere. A client
         *     that shows a score can always show what the score does not mean.
         */
        ModelInfo: {
            /** Model Id */
            model_id: string;
            /** Task */
            task: string;
            /** Framework */
            framework: string;
            /** Feature Set Version */
            feature_set_version: string;
            /** Threshold */
            threshold: number;
            /**
             * Threshold Selected On
             * @description Which split the threshold was chosen on
             */
            threshold_selected_on: string;
            /** N Features */
            n_features: number;
            /**
             * Metrics
             * @description Numeric metrics only
             */
            metrics: {
                [key: string]: number;
            };
            /** Limitations */
            limitations: string[];
        };
        /**
         * Prediction
         * @description A model's output for this event.
         *
         *     ``score`` is a **discriminant**, not a probability. The training class
         *     balance is a choice rather than a physical prior, so the number cannot be
         *     read as "chance this is signal". See docs/SCIENTIFIC_INTEGRITY.md section 3.
         *     The threshold is carried alongside so the score is never shown bare.
         */
        Prediction: {
            /** Model Id */
            model_id: string;
            /** Task */
            task: string;
            /**
             * Score
             * @description Discriminant, not a probability
             */
            score: number;
            /** Threshold */
            threshold: number;
            /**
             * Classification
             * @enum {string}
             */
            classification: "signal-like" | "background-like";
            /** Feature Set Version */
            feature_set_version: string;
        };
        /**
         * Provenance
         * @description Where this event came from and how it was processed.
         */
        Provenance: {
            /** Dataset */
            dataset: string;
            /** Record Url */
            record_url: string;
            /** Doi */
            doi: string;
            /**
             * Licence
             * @default CC0-1.0
             */
            licence: string;
            /** Source File */
            source_file: string;
            /** Pipeline Version */
            pipeline_version: string;
            /**
             * Accessed
             * @description ISO date the source was downloaded
             */
            accessed: string;
        };
        /**
         * ReconstructedObject
         * @description One reconstructed particle or jet.
         *
         *     Momentum is stored in both collider coordinates (what the detector reports)
         *     and Cartesian components (what the renderer needs), because deriving one
         *     from the other in the browser would duplicate physics code that is already
         *     tested in Python. ``px``/``py``/``pz`` define the direction of the display
         *     ray; see the note on tracks below.
         */
        ReconstructedObject: {
            /** Id */
            id: number;
            /**
             * Type
             * @enum {string}
             */
            type: "muon" | "electron" | "jet" | "photon";
            /**
             * Charge
             * @description None where charge is not measured, e.g. jets
             */
            charge?: number | null;
            /**
             * Pt
             * @description Transverse momentum, GeV
             */
            pt: number;
            /**
             * Eta
             * @description Pseudorapidity
             */
            eta: number;
            /**
             * Phi
             * @description Azimuthal angle, radians
             */
            phi: number;
            /**
             * Energy
             * @description Energy, GeV
             */
            energy: number;
            /** Px */
            px: number;
            /** Py */
            py: number;
            /** Pz */
            pz: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_events_api_events_get: {
        parameters: {
            query?: {
                /** @description Filter by real collision data or simulation */
                data_kind?: ("measured" | "simulated") | null;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_event_api_events__event_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                event_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventPayload"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_distribution_api_distributions__quantity__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quantity: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_models_api_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
}
